apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - name: backend
        image: file-uploader-backend:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: uploader-pvc