apiVersion: apps/v1
kind: Deployment
metadata: { name: uploader-frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: uploader-frontend } }
  template:
    metadata: { labels: { app: uploader-frontend } }
    spec:
      containers:
      - name: frontend
        image: uploader-frontend:latest
        imagePullPolicy: Never
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata: { name: uploader-frontend-svc }
spec:
  type: NodePort
  selector: { app: uploader-frontend }
  ports: [{ port: 80, targetPort: 80, nodePort: 30000 }]